### ISSUE TITLE
Failed to Compile

### ISSUE THREAD

**Issue by undpeter** [sgan81/apfs-fuse#11]
I installed:
cmake
fuse
icu
cmake-rpm-macros 
cmake-gui 
extra-cmake-modules
libattr-devel
libicu-devel

But when I try to compile it on Fedora KDE 27, it fails to compile.

[ 89%] Building CXX object apfsfuse/CMakeFiles/apfs-fuse.dir/ApfsFuse.cpp.o
cd /home/uit/apfs-fuse/build/apfsfuse && /usr/bin/c++  -D_FILE_OFFSET_BITS=64 -I/home/uit/apfs-fuse/.  -Wall -Wextra -march=native   -std=gnu++11 -o CMakeFiles/apfs-fuse.dir/ApfsFuse.cpp.o -c /home/uit/apfs-fuse/apfsfuse/ApfsFuse.cpp
/home/uit/apfs-fuse/apfsfuse/ApfsFuse.cpp:22:10: fatal error: fuse/fuse.h: No such file or directory
 #include <fuse/fuse.h>
          ^~~~~~~~~~~~~
compilation terminated.
make[2]: *** [apfsfuse/CMakeFiles/apfs-fuse.dir/build.make:66: apfsfuse/CMakeFiles/apfs-fuse.dir/ApfsFuse.cpp.o] Error 1
make[2]: Leaving directory '/home/uit/apfs-fuse/build'
make[1]: *** [CMakeFiles/Makefile2:254: apfsfuse/CMakeFiles/apfs-fuse.dir/all] Error 2
make[1]: Leaving directory '/home/uit/apfs-fuse/build'
make: *** [Makefile:87: all] Error 2

**Comment by Johnnie390** [comment]
You are missing libfuse-dev or one of its variants most likely.

**Comment by undpeter** [comment]
Installing fuse-devel fixed the issue.  Thanks for the help.
