### ISSUE TITLE
I want read a apfs-disk/dmg on windows.

### ISSUE THREAD

**Issue by vusarath** [sgan81/apfs-fuse#111]
I want read a apfs-disk/dmg on windows.

Is this the correct tool for doing it .

**Comment by Banaanhangwagen** [comment]
No. 
You should look at another solution for that. Simply google "apfs windows", and literally the first hit is what you are looking for.

**Comment by theLMGN** [comment]
...all of which are commercial

**Comment by RJVB** [comment]
Including the OS so that can hardly be an issue here.

**Comment by theLMGN** [comment]
> Including the OS so that can hardly be an issue here.
Sometimes, you just gotta use Windows.

**Comment by ydkhatri** [comment]
> Sometimes, you just gotta use Windows, and sometimes, you need the files off an APFS volume.
If that is all you need, use a tool like "FTK Imager" or "Autopsy", both free windows gui tools which will mount APFS disks for you and let you export files/folders. Google them.
