### ISSUE TITLE
Device not found!

### ISSUE THREAD

**Issue by AJenbo** [sgan81/apfs-fuse#12]
Running:
`$ ./apfs-fuse -d 1 /dev/sda2 /home/ajenbo/cmbp`
results in:
> Device not found!

I have verified that the partition-type is 7c3457ef-0000-11aa-aa11-00306543ecac

**Comment by sgan81** [comment]
Do you have the proper access rights to the device?

**Comment by AJenbo** [comment]
The same happens when running the command with sudo

**Comment by sgan81** [comment]
Can you try the new version? It should be somewhat more verbose telling you what went wrong ...

**Comment by AJenbo** [comment]
Sorry the mac I was working on has been returned to its owner (managed to get the drive working via a USB enclosure), but I will give it a shot at the next opportunity I have.

The drive was upgraded from hfs+

**Comment by sgan81** [comment]
I never tested with updated drives, but it works on iOS installation images, and those seem to have been updated from HFS+ as well ... so that should not be the problem. Although iOS images use the version of APFS that macOS 10.12 used.

**Comment by sgan81** [comment]
I'm closing this issue now. If you still encounter problems next time you try, please report them.
