### ISSUE TITLE
Invalid Opcode on AMD architecture

### ISSUE THREAD

**Issue by brucemarkey** [sgan81/apfs-fuse#120]
Application crashes with "Invalid Opcode" when running on an AMD architecture.  The problem appears to be in libapfs.so, according to dmesg (possibly Util.cpp, Unicode.cpp or Crc32.cpp).

**Comment by sgan81** [comment]
Odd ... can you try removing the -march=native build option from the CMakeLists.txt (lines 13 and 14) and try again?
If this solves the problem, it might be an issue in the compiler ...

**Comment by brucemarkey** [comment]
Removing the -march=native build option from the CMakeLists.txt fixes this as the compiler does not use optimisations specific to the processor used to compile the code.

**Comment by RJVB** [comment]
Correct, `-march=native` should be avoided when building distributable binaries. It does make sense on local builds though.

**Comment by sgan81** [comment]
I have now pushed a makefile change and removed the -march=native.
