### ISSUE TITLE
Create APFS images linux

### ISSUE THREAD

**Issue by 404meemr** [sgan81/apfs-fuse#122]
Is there a way to create APFS formatted images on linux? I found out that mkfs doesn't support APFS, so I don't know how to create APFS images without a Mac.

**Comment by 404meemr** [comment]
I now realize that this probably is impossible

**Comment by Luflosi** [comment]
This should be able to create an APFS filesystem on Linux: https://github.com/linux-apfs/apfsprogs. It's available in the AUR in case you're using Arch Linux.

**Comment by 404meemr** [comment]
Oh thanks. It turns out that Apple explicitly disallows people from using the APFS spec for purposes outside developing for apple devices.
