### ISSUE TITLE
This doesn't seem to be an apfs volume (invalid superblock)

### ISSUE THREAD

**Issue by ManuLinares** [sgan81/apfs-fuse#123]
gnome-disk-utils shows is a "Apple Core Storage" partition

```
[]# apfs-fuse /dev/sdb2 /mnt
This doesn't seem to be an apfs volume (invalid superblock).
Unable to load container.
```

fdisk -l
```
Disk /dev/sdb: 298.9 GiB, 320072933376 bytes, 625142448 sectors
Disk model: Hitachi HTS54503
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: gpt
Disk identifier: DB1D4C17-1B7D-42F9-B17D-550806BB3B1B

Device         Start       End   Sectors   Size Type
/dev/sdb1         40    409639    409600   200M EFI System
/dev/sdb2     409640 623872871 623463232 297.3G Apple Core storage
/dev/sdb3  623872872 625142407   1269536 619.9M Apple boot

```

My Macbook pro with "MacOS 10.13.6" died on me, so I'm gonna try installing a MacOS Catalina on a vm with libvirtio-qemu-kvm.

**Comment by Banaanhangwagen** [comment]
If I'm not mistaken, Apple Core storage uses the HFS+ filesystem (and not APFS).
You should try https://github.com/libfuse/libfuse in order to mount.

**Comment by sgan81** [comment]
Yes, CoreStorage uses HFS+. I don't know about software that is able to handle CoreStorage volumes, but you may find some.
@Banaanhangwagen I don't think the fuse library will help much in this case ;)

**Comment by ManuLinares** [comment]
I created a MacOS VM, mounted the disk on DiskUtility and decrypted the disk into a DMG file... then converted to IMG and mounted successfully.
