### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by Falcone8** [sgan81/apfs-fuse#141]
[ 87%] Building CXX object CMakeFiles/apfs-fuse.dir/apfsfuse/ApfsFuse.cpp.o
/home/anon/Scaricati/apfs-fuse/apfsfuse/ApfsFuse.cpp:31:10: fatal error: fuse3/fuse.h: File o directory non esistente
   31 | #include <fuse3/fuse.h>
      |          ^~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/apfs-fuse.dir/build.make:82: CMakeFiles/apfs-fuse.dir/apfsfuse/ApfsFuse.cpp.o] Errore 1
make[1]: *** [CMakeFiles/Makefile2:134: CMakeFiles/apfs-fuse.dir/all] Errore 2
make: *** [Makefile:149: all] Errore 2

**Comment by Yuki-Zukheo** [comment]
How did you solve the Problem?
