### ISSUE TITLE
Just want to say thanks!

### ISSUE THREAD

**Issue by lmartinking** [sgan81/apfs-fuse#16]
You saved my bacon tonight! I had a APFS based volume on sparse bundle on a exfat USB drive, and only a linux machine on-hand, and I was able to get my files out of it using `apfs-fuse` and `sparsebundlefs` and `fuse-exfat`.

For future readers benefit: I had to create a loopback mount as the actual APFS data was offset. The `sparsebundlefs` README shows how.

Again, thank you so much! I am really relieved!

**Comment by sgan81** [comment]
You are welcome :-)
