### ISSUE TITLE
Suspicious lowercasing logic used to compute file name hashes

### ISSUE THREAD

**Issue by trejkaz** [sgan81/apfs-fuse#17]
I noticed that the lowercasing logic in the file hash code had a hard-coded 0x500-element array, and decided to try and make a contradicting test case.

```
hdiutil create -megabytes 1 -layout GPTSPUD -fs apfs -volname unicode-name-edge-cases unicode-name-edge-cases.dmg
hdiutil attach unicode-name-edge-cases.dmg
# U+1EE2 = Latin Capital Letter O With Horn And Dot Below
touch /Volumes/unicode-name-edge-cases/$'\xE1\xBB\xA2'_$'\xE1\xBB\xA2'
# U+1EE3 = Latin Small Letter O With Horn And Dot Below
touch /Volumes/unicode-name-edge-cases/$'\xE1\xBB\xA3'_$'\xE1\xBB\xA3'
ls -l /Volumes/unicode-name-edge-cases
```

Output for me was like this:

```
drwx------  3 tester  staff   96 15 Mar 11:00 .fseventsd
-rw-r--r--  1 tester  staff    0 15 Mar 11:01 Ợ_Ợ
```

This confirms that characters _above_ 0x500 are also lowercased.
Now I'm doing further investigation to see just how high it goes.

**Comment by trejkaz** [comment]
Further cases. I'll include the directory listings created when using Apple's apfs driver.
Many of these may already be covered in apfs-fuse already because ICU is being used to do the heavy lifting.

Normalised forms:

```
touch /Volumes/unicode-name-edge-cases/normalisation_forms_$'\xC3\xA9'
touch /Volumes/unicode-name-edge-cases/normalisation_forms_e$'\xCC\x81'
```

Results in one entry:

```
-rw-r--r--   1 tester  staff    0 15 Mar 11:26 normalisation_forms_é
```

Compatibility normalised forms:

```
touch /Volumes/unicode-name-edge-cases/compatibility_forms_$'\xEF\xAC\x83'
touch /Volumes/unicode-name-edge-cases/compatibility_forms_ffi
```

Results in one entry (interesting because usually you would not do this unless converting to uppercase, implying that maybe what's going on is some kind of uppercasing, not lowercasing):

```
-rw-r--r--   1 tester  staff    0 15 Mar 11:26 compatibility_forms_ﬃ
```

German hard ß with its unused capital friend:

```
touch /Volumes/unicode-name-edge-cases/german_case_folding_$'\xC3\x9F'
touch /Volumes/unicode-name-edge-cases/german_case_folding_$'\xE1\xBA\x9E'
touch /Volumes/unicode-name-edge-cases/german_case_folding_SS
```

Surprisingly, all of these result in the one entry as well:

```
-rw-r--r--   1 tester  staff    0 15 Mar 11:26 german_case_folding_ß
```

And perhaps the _most_ interesting one, Turkish:

```
touch /Volumes/unicode-name-edge-cases/turkish_case_folding_$'\xC4\xB1'
touch /Volumes/unicode-name-edge-cases/turkish_case_folding_i
touch /Volumes/unicode-name-edge-cases/turkish_case_folding_I
touch /Volumes/unicode-name-edge-cases/turkish_case_folding_$'\xC4\xB0'
```

Here I get three entries, where I had expected one:

```
-rw-r--r--   1 tester  staff    0 15 Mar 11:26 turkish_case_folding_i
-rw-r--r--   1 tester  staff    0 15 Mar 11:26 turkish_case_folding_İ
-rw-r--r--   1 tester  staff    0 15 Mar 11:26 turkish_case_folding_ı
```

**Comment by trejkaz** [comment]
Throwing in a bonus one. This one should completely eliminate the temptation to do it as a simple array lookup. ;)

```
# \xF0\x9E\xA4\x9F = U+1E91F = Adlam Capital Letter Zal
# \xF0\x9E\xA5\x81 = U+1E941 = Adlam Small Letter Zal
touch /Volumes/unicode-name-edge-cases/lowercase_surrogate_$'\xF0\x9E\xA4\x9F'
touch /Volumes/unicode-name-edge-cases/lowercase_surrogate_$'\xF0\x9E\xA5\x81'
```

It unifies too.

```
-rw-r--r--  1 tester  staff    0 15 Mar 11:38 lowercase_surrogate_𞤟
```

**Comment by trejkaz** [comment]
My guess for the actual logic (this works for all test cases so far, using the Java version of ICU, so I don't know how to write it in C++):

* Inputs: string bytes, length, case insensitive flag
* Get a Unicode string from the bytes and length using UTF-8
* Chop NUL from the end
* If case insensitive:
    * Perform ICU "case fold" with the default settings
* Perform ICU normalisation to NFD
* Convert back to UTF-32LE and hash that

**Comment by sgan81** [comment]
Well, I reverse-engineered that part ... and case folding happens after normalization (at least in Apple's apfs driver), which might make some difference ...

If the case folding algorithm is not correct, the apfs-fuse driver is unable to find files. I didn't test as extensive as you did, though I might try your test cases later ...

**Comment by trejkaz** [comment]
Hmm, interesting. I wonder if I can dig up a test case which shows a difference between case folding before and after...

**Comment by sgan81** [comment]
Well, you were actually correct in saying that I overlooked some things ... found a few hashes that didn't match. Will need to fix that, but it might take some time ...

**Comment by sgan81** [comment]
Case folding should work better now, since I let ICU do it. You are of course welcome to test if you want ;-)
