### ISSUE TITLE
Installing APFS-Fuse on a chromebook with Penguin Linux installed [I think]

### ISSUE THREAD

**Issue by XY43137** [sgan81/apfs-fuse#173]
Please, need help urgently.

I am trying to install this in a linux virtual on my chromebook. I want to transfer files from an APFS drive to ExFat externals I have plugged in. I am a complete noob to Terminal, other than commands I used to use on Macbooks, which I now despise. Long time coming. 

The code I get is:
xy@penguin:~/apfs-fuse/build$ mkdir build
cd build
cmake ..
ccmake . # Only if you want to change build options
make
mkdir: cannot create directory ‘build’: File exists
-- Configuring done
-- Generating done
-- Build files have been written to: /home/xy/apfs-fuse/build
-bash: ccmake: command not found
[ 16%] Built target lzfse
[ 18%] Building CXX object CMakeFiles/apfs.dir/ApfsLib/Util.cpp.o
/home/xy/apfs-fuse/ApfsLib/Util.cpp:36:10: fatal error: 'zlib.h' file not found
#include <zlib.h>
         ^~~~~~~~
1 error generated.
make[2]: *** [CMakeFiles/apfs.dir/build.make:446: CMakeFiles/apfs.dir/ApfsLib/Util.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:217: CMakeFiles/apfs.dir/all] Error 2
xy@penguin:~/apfs-fuse/build$ Error 2
-- Configuring done
-- Generating done
-- Build files have been written to: /home/xy/apfs-fuse/build
-bash: ccmake: command not found
make: *** No targets specified and no makefile found.  Stop.
-bash: mkdir:: command not found
-bash: --: command not found
-bash: --: command not found
-bash: --: command not found
-bash: -bash:: command not found
-bash: [: missing `]'
-bash: [: missing `]'
-bash: /home/xy/apfs-fuse/ApfsLib/Util.cpp:36:10:: No such file or directory
-bash: ^~~~~~~~: command not found
-bash: 1: command not found
-bash: make[2]:: command not found
-bash: make[1]:: command not found
-bash: make:: command not found
-bash: xy@penguin:~/apfs-fuse/build$: No such file or directory
xy@penguin:~/apfs-fuse/build/build$ cd ~/apfs-fuse/build
xy@penguin:~/apfs-fuse/build$ cd /apfs-fuse/ApfsLib/
-bash: cd: /apfs-fuse/ApfsLib/: No such file or directory
xy@penguin:~/apfs-fuse/build$ sudo apt install zlib
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package zlib
xy@penguin:~/apfs-fuse/build$ sudo apt install zlib1g
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
zlib1g is already the newest version (1:1.2.11.dfsg-2+deb11u2).
0 upgraded, 0 newly installed, 0 to remove and 19 not upgraded.
xy@penguin:~/apfs-fuse/build$ mkdir build
cd build
cmake ..
make
mkdir: cannot create directory ‘build’: File exists
-- Configuring done
-- Generating done
-- Build files have been written to: /home/xy/apfs-fuse/build
make: *** No targets specified and no makefile found.  Stop.
xy@penguin:~/apfs-fuse/build/build$ cd XX
-bash: cd: XX: No such file or directory
xy@penguin:~/apfs-fuse/build/build$ apfs-fuse /dev /XX/ 
-bash: apfs-fuse: command not found
xy@penguin:~/apfs-fuse/build/build$ 

I installed the zlib1g option as zlib didn't work. 

Any way to get this going? I am trying very hard to no longer use macOS.

PS: Did I pujt the zlib in the right place?

Regards,

Frederick.

![Screenshot 2023-02-06 19 02 22](https://user-images.githubusercontent.com/76269339/216917092-c2ef9c0e-d3ed-470a-99b9-83ce7af49652.png)

**Comment by sgan81** [comment]
There is no reason to mkdir build if you are already inside the build directory ...

If it shows ~/apfs-fuse/build on the left, you are in the correct place. In there, you do cmake .., followed by make. If you already did cmake before, make is enough.

**Comment by XY43137** [comment]
Jesus  dude. I'm not a coder. I don't know why 7 get 2 bills folders. I don't understand what the fuck you are saying. Anyway, I got rid of the Chromebook. Pieces of junk. It doesn't matter anymore.  FREDERICK MALOUF  XO  PO BOX 7434   BONDI BEACH   NSW   2026   AUSTRALIA +61 403 993 699How would I define myself? That’s like asking the definition of infinity …
-------- Original message --------From: Simon Gander ***@***.***> Date: 13/3/23  00:07  (GMT+10:00) To: sgan81/apfs-fuse ***@***.***> Cc: XO ***@***.***>, Author ***@***.***> Subject: Re: [sgan81/apfs-fuse] Installing APFS-Fuse on a chromebook with Penguin Linux installed [I think] (Issue #173) 
There is no reason to mkdir build if you are already inside the build directory ...
If it shows ~/apfs-fuse/build on the left, you are in the correct place. In there, you do cmake .., followed by make. If you already did cmake before, make is enough.

**Comment by XY43137** [comment]
You arre saying what you expect to happen, not that it didn't. Who cares. I'm not getting another Chromebook. Stupid fucking things.  FREDERICK MALOUF  XO  PO BOX 7434   BONDI BEACH   NSW   2026   AUSTRALIA +61 403 993 699How would I define myself? That’s like asking the definition of infinity …
-------- Original message --------From: Simon Gander ***@***.***> Date: 13/3/23  00:07  (GMT+10:00) To: sgan81/apfs-fuse ***@***.***> Cc: XO ***@***.***>, Author ***@***.***> Subject: Re: [sgan81/apfs-fuse] Installing APFS-Fuse on a chromebook with Penguin Linux installed [I think] (Issue #173) 
There is no reason to mkdir build if you are already inside the build directory ...
If it shows ~/apfs-fuse/build on the left, you are in the correct place. In there, you do cmake .., followed by make. If you already did cmake before, make is enough.
