### ISSUE TITLE
Easy way to make some spurious warnings go away

### ISSUE THREAD

**Issue by Ndolam** [sgan81/apfs-fuse#18]
I always get worried when I see warning messages like this fly by:

/local/src/sys/apfs-fuse-master/ApfsLib/BTree.cpp:508:35: warning: ‘rc’ may be used uninitialized in this function [-Wmaybe-uninitialized]
   res = (rc > 0) ? mid : (mid + 1);

Looking at the code, I see that (assuming cnt can't be < 0) they are spurious, and if my version of gcc was smarter, it wouldn't output them.

However, they will go away (at least in gcc v 5.5.0) if you change 
	if (cnt == 0)
		return -1;
to
    if (cnt < 1)
		return -1;

This also protects against the possibly-can-never-and-should-never-happen case of cnt < 0.

Thanks for your efforts on this!

**Comment by sgan81** [comment]
Should be fixed now :-)
