### ISSUE TITLE
Contact?

### ISSUE THREAD

**Issue by tempelmann** [sgan81/apfs-fuse#2]
Hi,
I've been doing APFS rev-eng as well (see https://github.com/cugu/apfs.ksy/graphs/contributors), also am in the middle of releasing some software for it. Are you interested in sharing information? Then please make contact - see my profile.

**Comment by Johnnie390** [comment]
Tested SGAN81's APFS-Fuse implementation on Debian Buster using a 4.15 kernel. The utility works loke a charm. I am able to "see" everything and copy files to a normal EXT4 file system. As of writing, (31.12.2017), no corrupted files experienced on the mount point. Chapeau!!

**Comment by Johnnie390** [comment]
Correction.

**Comment by sgan81** [comment]
Hi,
Of course we can share information if you want. I don't have much documentation though, it's all in the code ... but feel free to write if you want to know something.
