### ISSUE TITLE
Unknown Inode Attribute 2203/2003/203 when reading files

### ISSUE THREAD

**Issue by dents** [sgan81/apfs-fuse#20]
Looking at logs after trying to copy a lot of files, I'm seeing lots of messages like this:
WARNING!!!: Unknown Inode Attribute 2203 at inode ...
WARNING!!!: Unknown Inode Attribute 2003 at inode ...
WARNING!!!: Unknown Inode Attribute 203 at inode ...

Also apfs-dump-quick spit out a bunch of these:
!!! UNKNOWN NODE TYPE 2147483666 in block ...

**Comment by sgan81** [comment]
Well, those messages all mean that I never encountered these types of data and therefore wasn't able to analyze it ... do you have any special options active for the volume? Or special kinds of files?

**Comment by dents** [comment]
It was converted from an HFS+ volume, other than that nothing special as far as I know. Didn't specify any options at all when mounting. Any way I can provide more info?

**Comment by sgan81** [comment]
Well, what you reported are actually two issues. You could provide more info for both as follows:

Run the apfs-dump-quick tool.

You could then compress the whole dump file and send it to me, but it is big and contains all your filenames, so ... not that much privacy I guess. So, I suggest the following:

Unknown Node Type 2147483666 (= 40000012 Hex):
Look for node types 40000012 in the dump (node headers). Should be followed by a hex dump of 4096 (1000 hex) bytes. I can use that hex dump.

Unknown Inode Attribute:
Search for the String [!!!] in the dump file. In the parts where the directory structure is dumped, you should find entries containing these strings. I need those entries.

So just copy-paste the information mentioned above into a file and send it to me for analysis.

Also, I would recommend not deleting the dump file afterwards, I might be asking for more info ;-)

Thanks for your help :-)

**Comment by fredcooke** [comment]
@dents Did you get a chance to pass some data back to Simon yet?

**Comment by dents** [comment]
@fredcooke Nope not yet.

**Comment by sgan81** [comment]
After releasing of the specs by Apple, the meaning of these fields is clear, so I'm going to close this issue now (better late than never ...).
