### ISSUE TITLE
Fragmented files, FileVault, recovery keys and more

### ISSUE THREAD

**Issue by puccia** [sgan81/apfs-fuse#22]
Hello!

Simon, thanks for this awesome FUSE driver.

Opening this issue to discuss pull request #21 . If it's too big or there are other problems, I'm happy to split it up or to fix the problems :)

Copying here the content of the main deltas for convenience:

1. Allow mounting of FileVault-encrypted APFS volumes, as opposed to regular encrypted volumes;
1. Allow decryption through a (personal, not institutional) recovery key, as opposed to a regular password;
1. Fix decryption when an extent's crypto_id does not match the block number;
1. Fix reading fragmented files;
1. Fix decompression for several algos, especially the handling of uncompressed blocks;
1. Provide a "strict" mode that returns errors when decompression fails;
1. Minor enhancements (allow spaces in passwords; allow specifying a container offset, which is handy when working with raw disk images).

**Comment by sgan81** [comment]
Hi Emanuele

Thanks for the fixes. I have merged your pull request, after fixing some ... well ... cosmetics.

Apart from fixing formatting, I also changed a few small details:
- I recommend not using C-Style casts in C++
- Replaced "\n" with std::endl when outputting strings to std::cout / std::cerr

Grazie mille ;-)

**Comment by puccia** [comment]
Merci vielmal, Simon!;)

Also for taking care of the formatting – I've seen what you changed and next time I'll keep the style preferences in mind (besides the tab issues). I definitely didn't want to make you take care of that :)

If you work in Zürich or if it's handy for you at some point, you should totally swing by for lunch!

**Comment by sgan81** [comment]
Above question is of course for your filevault volume, for which you implemented your changes. If I interpret your changes correctly, the KEK is 256 and the VEK 128 bits long. On my test volume, both keys are 128 bit.

By the way, the newest version I uploaded dumps the keybags in parsed form, if you specify the debug flag.

**Comment by puccia** [comment]
Unfortunately I don't have access to that disk image right now but I'll try to regain it, so that I can answer your question!

My current (limited) understanding is that the KEK is always 256 bits long. Conversely, the length of the VEK is variable. When the volume is "normally" encrypted (i.e. create a new volume and specify encryption as an option), the VEK is 256 bits long and provides both the "data" and the "tweak" AES-XTS keys.

When it is a FileVault volume, the VEK is 128 bit long, and provides the "data" key. The "tweak" key is generated from it and from another piece of binary data that looks like a UUID, but I am not sure what it is exactly for.

I used the following references:

https://www.cl.cam.ac.uk/~osc22/docs/slides_fv2_ifip_2013.pdf
https://github.com/libyal/libfvde/blob/master/documentation/FileVault%20Drive%20Encryption%20(FVDE).asciidoc

**Comment by sgan81** [comment]
Ok, thanks.

This is what the keybags look like on my test volume:

```
Dumping Keybag (keys)

0000: 02 00 02 00 80 01 00 00 00 00 00 00 00 00 00 00 - ................
0010: 5B 5F 38 57 85 1B 3B B4 96 8A FB A9 4E 5F 52 FF - [_8W..;.....N_R.
0020: 03 00 10 00 00 00 00 00 BF 3B 00 00 00 00 00 00 - .........;......
0030: 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 - ................
0040: 5B 5F 38 57 85 1B 3B B4 96 8A FB A9 4E 5F 52 FF - [_8W..;.....N_R.
0050: 02 00 20 01 00 00 00 00 30 7A 80 01 00 81 20 B3 - .. .....0z.... .
0060: 32 70 B4 4C 34 EA 25 FF C3 45 4D 5A A6 90 93 BA - 2p.L4.%..EMZ....
0070: A5 A9 1E EA FC CA DC 8E 91 5D 24 BE 7A 32 D8 82 - .........]$.z2..
0080: 08 C9 55 C3 6D 05 4F 41 AC A3 49 80 01 00 81 10 - ..U.m.OA..I.....
0090: 03 AE 7B 2F 5D E7 44 BD 90 8D BA DE 5C 4B 8A 06 - ..{/].D.....\K..
00A0: 82 08 02 00 00 00 01 00 28 55 83 28 28 7E C9 62 - ........(U.((~.b
00B0: F7 C9 95 D3 34 E5 B6 61 53 B6 1F 2C B5 D9 CC 32 - ....4..aS..,...2
00C0: 7E 5B 46 24 00 00 00 00 00 00 00 00 00 00 00 00 - ~[F$............
00D0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 - ................
00E0: 0B 00 00 00 00 00 13 00 C1 16 10 A2 FF FF 1D 00 - ................
00F0: 8C 07 60 00 00 00 00 00 06 4F 6E 6C 69 6E 65 00 - ..`......Online.
0100: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 40 - ...............@
0110: 23 01 85 52 FA 07 1E 00 C1 16 10 A2 FF FF 1D 00 - #..R............
0120: 8C 07 60 00 00 00 00 00 24 45 30 38 43 39 43 38 - ..`.....$E08C9C8
0130: 37 2D 42 36 34 31 2D 34 33 34 36 2D 42 42 36 32 - 7-B641-4346-BB62
0140: 2D 34 36 33 31 45 42 42 30 42 34 38 35 00 00 00 - -4631EBB0B485...
0150: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 40 - ...............@
0160: 00 00 00 00 00 00 00 40 08 00 00 00 00 00 00 00 - .......@........
0170: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 - ................

Version : 0002
Keys    : 0002
Bytes   : 00000180

Key 0:
UUID    : 5B5F3857-851B-3BB4-968A-FBA94E5F52FF
Type    : 0003 [Keybag Ref]
Length  : 0010
Unknown : 00000000

Block   : 0000000000003BBF
Count   : 0000000000000001

Key 1:
UUID    : 5B5F3857-851B-3BB4-968A-FBA94E5F52FF
Type    : 0002 [VEK]
Length  : 0120
Unknown : 00000000

[Blob Header]
Unk 80  : 0
HMAC    : B33270B44C34EA25FFC3454D5AA69093BAA5A91EEAFCCADC8E915D24BE7A32D8
Salt    : C955C36D054F41AC
Data    :
0000: A3 49 80 01 00 81 10 03 AE 7B 2F 5D E7 44 BD 90 - .I.......{/].D..
0010: 8D BA DE 5C 4B 8A 06 82 08 02 00 00 00 01 00 28 - ...\K..........(
0020: 55 83 28 28 7E C9 62 F7 C9 95 D3 34 E5 B6 61 53 - U.((~.b....4..aS
0030: B6 1F 2C B5 D9 CC 32 7E 5B 46 24 00 00 00 00 00 - ..,...2~[F$.....
0040: 00 00 00 00 00 00 00 00 00 00 00                - ...........

[VEK]
Unk 80  : 0
UUID    : 03AE7B2F-5DE7-44BD-908D-BADE5C4B8A06
Unk 82  : 00000002 0001 28 55
VEK Wrpd: 287EC962F7C995D334E5B66153B61F2CB5D9CC327E5B462400000000000000000000000000000000



Dumping Keybag (recs)

0000: 02 00 01 00 C0 00 00 00 00 00 00 00 00 00 00 00 - ................
0010: 5B 5F 38 57 85 1B 3B B4 96 8A FB A9 4E 5F 52 FF - [_8W..;.....N_R.
0020: 03 00 94 00 00 00 00 00 30 81 91 80 01 00 81 20 - ........0...... 
0030: EB 03 5F 25 43 8B 2E 28 5F 3C 50 07 74 FD 95 A4 - .._%C..(_<P.t...
0040: AB 03 8B 9C 71 20 D9 84 BC 94 38 73 B7 08 10 BD - ....q ....8s....
0050: 82 08 7A BF 10 5F 4D BE 83 6C A3 60 80 01 00 81 - ..z.._M..l.`....
0060: 10 03 AE 7B 2F 5D E7 44 BD 90 8D BA DE 5C 4B 8A - ...{/].D.....\K.
0070: 06 82 08 02 00 00 00 02 00 28 55 83 28 B4 88 D3 - .........(U.(...
0080: 30 2A 9B 19 65 7D 15 88 30 33 FF 2C 9D D3 80 8C - 0*..e}..03.,....
0090: 34 76 9B 92 09 00 00 00 00 00 00 00 00 00 00 00 - 4v..............
00A0: 00 00 00 00 00 84 03 02 41 0A 85 10 DD 95 99 D0 - ........A.......
00B0: 5C 9F 08 BF 2A 7B E1 26 C0 9A EC 4D 00 00 00 00 - \...*{.&...M....

Version : 0002
Keys    : 0001
Bytes   : 000000C0

Key 0:
UUID    : 5B5F3857-851B-3BB4-968A-FBA94E5F52FF
Type    : 0003 [KEK]
Length  : 0094
Unknown : 00000000

[Blob Header]
Unk 80  : 0
HMAC    : EB035F25438B2E285F3C500774FD95A4AB038B9C7120D984BC943873B70810BD
Salt    : 7ABF105F4DBE836C
Data    :
0000: A3 60 80 01 00 81 10 03 AE 7B 2F 5D E7 44 BD 90 - .`.......{/].D..
0010: 8D BA DE 5C 4B 8A 06 82 08 02 00 00 00 02 00 28 - ...\K..........(
0020: 55 83 28 B4 88 D3 30 2A 9B 19 65 7D 15 88 30 33 - U.(...0*..e}..03
0030: FF 2C 9D D3 80 8C 34 76 9B 92 09 00 00 00 00 00 - .,....4v........
0040: 00 00 00 00 00 00 00 00 00 00 00 84 03 02 41 0A - ..............A.
0050: 85 10 DD 95 99 D0 5C 9F 08 BF 2A 7B E1 26 C0 9A - ......\...*{.&..
0060: EC 4D                                           - .M

[KEK]
Unk 80  : 0
UUID    : 03AE7B2F-5DE7-44BD-908D-BADE5C4B8A06
Unk 82  : 00000002 0002 28 55
KEK Wrpd: B488D3302A9B19657D15883033FF2C9DD3808C34769B920900000000000000000000000000000000
Iterat's: 147722
Salt    : DD9599D05C9F08BF2A7BE126C09AEC4D

[Decryption Check]
PW DKey : 00BFF51255EA026EF153A24EB353C6F58E46BA7B449605F617FD9209ACDFD433
KEK Dec : 829FC5277C05B834CB5F0068F8FDDBB700000000000000000000000000000000
IV KEK  : A6A6A6A6A6A6A6A6 [Correct]
VEK Dec : C65DCFB82FD25F2CC73BB49D1CEB96EC00000000000000000000000000000000
IV VEK  : A6A6A6A6A6A6A6A6 [Correct]
```

The decryption check is done using AES-128 both times, and as you can see, it generates the correct results. Also, the wrapped keys are obviously not 256 bits long, otherwise they wouldn't have all the zeroes at the end.

So, maybe you did something different than I did? Like I said, I created an encrypted HFS+ volume, from the Disk Utility, onto a USB stick. Then, also via the Disk Utility, I converted said stick to APFS, and got what I described above. However, the encryption on the HFS+ drive was done using CoreStorage, maybe that's the difference.

If you did it differently or know how whoever did it has done it, describing the necessary steps would also help ...

**Comment by sgan81** [comment]
Ok, yes, stupid me didn't use file vault, but CoreStorage encryption ...

Will test with FileVault now.

**Comment by puccia** [comment]
Ok, you were faster than my reply! :)

**Comment by sgan81** [comment]
Ok, I figured it out ... the KEK and VEK are both 128 bits after conversion. But if someone changes the password on the APFS volume, the new KEK is 256 bits long. In which case the value I wanted to know is 16. :-)

**Comment by sgan81** [comment]
By the way, there were some segfaults in Keybag::FindKey introduced by your changes ...
