### ISSUE TITLE
Not able to install on ubuntu 16.04

### ISSUE THREAD

**Issue by raghu777** [sgan81/apfs-fuse#23]
Hi,

I am not able install this on ubuntu 16.04. I am getting following error.

cd /home/ubuntu/apfs-fuse/build/apfsfuse && /usr/bin/c++   -D_FILE_OFFSET_BITS=64 -I/home/ubuntu/apfs-fuse/.  -std=c++11 -Wall -Wextra -march=native -O3 -DNDEBUG   -std=gnu++11 -o CMakeFiles/apfs-fuse.dir/ApfsFuse.o -c /home/ubuntu/apfs-fuse/apfsfuse/ApfsFuse.cpp
/home/ubuntu/apfs-fuse/apfsfuse/ApfsFuse.cpp:29:24: fatal error: attr/xattr.h: No such file or directory
compilation terminated.
apfsfuse/CMakeFiles/apfs-fuse.dir/build.make:65: recipe for target 'apfsfuse/CMakeFiles/apfs-fuse.dir/ApfsFuse.o' failed
make[2]: *** [apfsfuse/CMakeFiles/apfs-fuse.dir/ApfsFuse.o] Error 1
make[2]: Leaving directory '/home/ubuntu/apfs-fuse/build'
CMakeFiles/Makefile2:253: recipe for target 'apfsfuse/CMakeFiles/apfs-fuse.dir/all' failed
make[1]: *** [apfsfuse/CMakeFiles/apfs-fuse.dir/all] Error 2
make[1]: Leaving directory '/home/ubuntu/apfs-fuse/build'
Makefile:86: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by RUGMJ7443** [comment]
how did you fix this?
