### ISSUE TITLE
Terminal access

### ISSUE THREAD

**Issue by vaishnavmurthy** [sgan81/apfs-fuse#24]
Thanks for taking the time to create this, the project works great and is a real life saver. The only thing I'd like is control of the terminal (and if I'm being ambitions, a descriptive message) after the volume gets mounted successfully. Thanks in advance!

**Comment by sgan81** [comment]
Yes, that shouldn't be a big problem. I'll do that later. Probably just one line of code ;)

**Comment by sgan81** [comment]
Done :smiley: 
If no debug flag is specified, you get back the console now.

**Comment by vaishnavmurthy** [comment]
Awesome! Thanks a bunch
