### ISSUE TITLE
Device container format

### ISSUE THREAD

**Issue by thejohnha** [sgan81/apfs-fuse#3]
Hi, pardon my ignorance, but what format should the device be in?

I've tried for example these: /dev/sdx, /dev/sdx2, sdx, sdx2, ...
But I can't seem to mount it correctly.

On my computer, if I try this: `./apfs-fuse -v 2 -d 1 /dev/sdb /mnt/my_drive`
it says:
`Device /dev/sdb opened. Size is 1000727379968 bytes.`
`Segmentation fault (core dumped)`

I am trying to mount /dev/sdb on my machine.

Any help would be appreciated! Thank you so much.

**Comment by karengabrielyan** [comment]
The following works for me:
apfs-fuse /dev/sda2 /mnt/mydrive

My /dev/sda has 2 partitions: /dev/sda1 is the boot partition of Mac, and /dev/sda2 is the one with APFS container.

Command works just fine, I can list and read file contents from APFS.

**Comment by sgan81** [comment]
Maybe you could try to find out where it crashes. See the updated Readme for instructions.

**Comment by sgan81** [comment]
The segfault should be fixed by now, so I'm closing this issue.
