### ISSUE TITLE
Error on make: recipe for target 'all' failed

### ISSUE THREAD

**Issue by kvaDrug** [sgan81/apfs-fuse#31]
I'm trying to install on Ubuntu 16.04. Getting this errors after calling make:

/home/kvadrug/Documents/APFS-fuse/apfs-fuse/apfsfuse/ApfsFuse.cpp:23:23: fatal error: fuse/fuse.h: No such file or directory
compilation terminated.
apfsfuse/CMakeFiles/apfs-fuse.dir/build.make:65: recipe for target 'apfsfuse/CMakeFiles/apfs-fuse.dir/ApfsFuse.o' failed
make[2]: *** [apfsfuse/CMakeFiles/apfs-fuse.dir/ApfsFuse.o] Error 1
make[2]: Leaving directory '/home/kvadrug/Documents/APFS-fuse/apfs-fuse/build'
CMakeFiles/Makefile2:1274: recipe for target 'apfsfuse/CMakeFiles/apfs-fuse.dir/all' failed
make[1]: *** [apfsfuse/CMakeFiles/apfs-fuse.dir/all] Error 2
make[1]: Leaving directory '/home/kvadrug/Documents/APFS-fuse/apfs-fuse/build'
Makefile:86: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by dkarpo** [comment]
Hello.

It looks like you may just be missing libfuse-dev.  Can you confirm if you have libfuse-dev installed and if that corrects the issue?

**Comment by kvaDrug** [comment]
```
$ sudo apt list libfuse-dev

Listing... Done
libfuse-dev/xenial-updates 2.9.4-1ubuntu3.1 amd64
N: There is 1 additional version. Please use the '-a' switch to see it
```
It's installed.

**Comment by dkarpo** [comment]
Hello.

'apt list' is just showing you information about a package and it doesn't
necessarily mean it's installed.  ie. I don't have kde-standard installed
on my system:

  $ apt list kde-standard
  Listing... Done
  kde-standard/unstable 5:101 amd64

Can you send the output of:

  $ dpkg -l libfuse-dev

Derrick

**Comment by kvaDrug** [comment]
I installed libfuse-dev and now the `dpkg -l libfuse-dev` returns:

```
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-=================================
ii  libfuse-dev    2.9.4-1ubunt amd64        Filesystem in Userspace (developm

```
I'm getting the same error.
```
[ 97%] Building CXX object apfsfuse/CMakeFiles/apfs-fuse.dir/ApfsFuse.o
cd /home/kvadrug/Documents/APFS-fuse/apfs-fuse/build/apfsfuse && /usr/bin/c++   -D_FILE_OFFSET_BITS=64 -I/home/kvadrug/Documents/APFS-fuse/apfs-fuse/. -I/home/kvadrug/Documents/APFS-fuse/apfs-fuse/3rdparty/lzfse/src  -std=c++11 -Wall -Wextra -march=native -O3 -DNDEBUG   -std=gnu++11 -o CMakeFiles/apfs-fuse.dir/ApfsFuse.o -c /home/kvadrug/Documents/APFS-fuse/apfs-fuse/apfsfuse/ApfsFuse.cpp
/home/kvadrug/Documents/APFS-fuse/apfs-fuse/apfsfuse/ApfsFuse.cpp:36:24: fatal error: attr/xattr.h: No such file or directory
compilation terminated.
apfsfuse/CMakeFiles/apfs-fuse.dir/build.make:65: recipe for target 'apfsfuse/CMakeFiles/apfs-fuse.dir/ApfsFuse.o' failed
make[2]: *** [apfsfuse/CMakeFiles/apfs-fuse.dir/ApfsFuse.o] Error 1
make[2]: Leaving directory '/home/kvadrug/Documents/APFS-fuse/apfs-fuse/build'
CMakeFiles/Makefile2:1274: recipe for target 'apfsfuse/CMakeFiles/apfs-fuse.dir/all' failed
make[1]: *** [apfsfuse/CMakeFiles/apfs-fuse.dir/all] Error 2
make[1]: Leaving directory '/home/kvadrug/Documents/APFS-fuse/apfs-fuse/build'
Makefile:86: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by dkarpo** [comment]
Hello.

It looks like you are also missing 'libattr1-dev' so can you install that
and try your compile again?  Pretty much everything you need to compile
apfs-fuse is included if you install the following:

  $ sudo apt-get install g++ cmake make libicu-dev libfuse-dev libattr1-dev

Derrick

**Comment by kvaDrug** [comment]
Thanks, installing `libattr1-dev` did the trick. I think you should list all the dependences in the README.

**Comment by RockNHawk** [comment]
Hello, I have the same issue in raspberry with rasbperry OS and have 

    ii  libfuse-dev              2.9.7-1+deb9u2    armhf             Filesystem in Userspace (development)

and

     $ sudo apt-get install g++ cmake make libicu-dev libfuse-dev libattr1-dev

installed.

**Comment by RockNHawk** [comment]
@kvaDrug 
Hello, I have the same issue in raspberry with rasbperry OS and have 

    ii  libfuse-dev              2.9.7-1+deb9u2    armhf             Filesystem in Userspace (development)

and

     $ sudo apt-get install g++ cmake make libicu-dev libfuse-dev libattr1-dev

installed.



[ 16%] Built target lzfse
[ 81%] Built target apfs
[ 85%] Built target apfs-dump-quick
[ 91%] Built target apfs-dump
[ 93%] Building CXX object CMakeFiles/apfs-fuse.dir/apfsfuse/ApfsFuse.cpp.o
/app/apfs/apfs-fuse/apfsfuse/ApfsFuse.cpp:31:24: fatal error: fuse3/fuse.h: No such file or directory
 #include <fuse3/fuse.h>
                        ^
compilation terminated.
CMakeFiles/apfs-fuse.dir/build.make:62: recipe for target 'CMakeFiles/apfs-fuse.dir/apfsfuse/ApfsFuse.cpp.o' failed     make[2]: *** [CMakeFiles/apfs-fuse.dir/apfsfuse/ApfsFuse.cpp.o] Error 1
CMakeFiles/Makefile2:218: recipe for target 'CMakeFiles/apfs-fuse.dir/all' failed
make[1]: *** [CMakeFiles/apfs-fuse.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by dkarpo** [comment]
Hello.

You will need to install libfuse3-dev from the looks of it.

  $ sudo apt-get install libfuse3-dev

Derrick

**Comment by dkarpo** [comment]
I should have added, as of today, I think the following should install all
of the packages you need to compile apfs-fuse:

 $ sudo apt-get install g++ cmake make libicu-dev libfuse-dev libfuse3-dev
libattr1-dev zlib1g-dev libbz2-dev

Derrick

**Comment by RockNHawk** [comment]
@dkarpo 
 
Thank you !

libfuse3-dev package not found in Raspderry OS, but ubuntu have an arm version
https://packages.ubuntu.com/disco/libfuse3-dev

I will try to download the ubuntu package and use it.
