### ISSUE TITLE
Rescuing an APFS partition

### ISSUE THREAD

**Issue by jhoefs** [sgan81/apfs-fuse#33]
I got the error message "unable to get volume!", but with different details from the other thread. I posted an extensive report of the problem I am trying to solve, and my attempts to fix it, on the Ubuntu forums: 

https://ubuntuforums.org/showthread.php?t=2393046#post13771507

In my most recent attempt, I used dd again to extract just the APFS partition from the disk image (into file partition6.dmg), and then tried apfs-fuse again:

$ sudo ./apfs-fuse -r passphrase -l /media/jonathan/untitled1/partition6.dmg /media/mountpoint/
nid c0f995b6fda590f9 xid a192d26f90a27374 NOT FOUND!!!
Unable to get volume!

Any help you could give would be so appreciated! If you look on the Ubuntu Forum post, I have tried a whole bunch of things.

**Comment by sgan81** [comment]
Is the disk image read-only or even compressed? In this case you cannot use dd to extract partitions.

Judging from the output, apfs-fuse did find something, but not usable. Can you try again with debug enabled? (-d 8)

**Comment by sgan81** [comment]
You could also try 7-zip to extract the partition from the dmg file, and then mount the extracted image using apfs-fuse.
