### ISSUE TITLE
Install libattr before using make

### ISSUE THREAD

**Issue by froemken** [sgan81/apfs-fuse#40]
Hello,

I currently get following error while executing make

attr/xattr.h not found

Please add to Readme:

sudo apt-get install libattr1-dev 

Nice greeting 

Stefan

**Comment by KAMiKAZOW** [comment]
> Please add to Readme:
> sudo apt-get install libattr1-dev

That would be Debian-specific.

**Comment by froemken** [comment]
I close this issue. If someone has this problem he/she will hopefully find that issue by google

**Comment by sgan81** [comment]
I will mention it in the readme for the next commit. Be patient ;)

**Comment by KAMiKAZOW** [comment]
Then merge #41 …
