### ISSUE TITLE
Input/output error

### ISSUE THREAD

**Issue by GH-Help** [sgan81/apfs-fuse#42]
Trying to access files contained within a .app file generates an Input/output error.  This is what debugging shows:

apfs_lookup: ino=1 name=root => OK
    apfs_stat_internal => OK
apfs_lookup: ino=2 name=Users => OK
    apfs_stat_internal => OK
apfs_lookup: ino=6691D name=username => OK
    apfs_stat_internal => OK
apfs_lookup: ino=6D4A8 name=Downloads => OK
    apfs_stat_internal => OK
apfs_lookup: ino=6D4AB name=Email Archiver Pro.app => OK
    apfs_stat_internal => OK
apfs_lookup: ino=100180F09 name=Contents => OK
    apfs_stat_internal => OK
apfs_lookup: ino=100180F0A name=Info.plist => OK
GetAttribute: type=11
parsing as a link
 size=379 size_on_disk=1000
 inode says size=0 size_on_disk=0
dumping attribute link data
0000: 66 0F 18 00 01 00 00 00 79 03 00 00 00 00 00 00 - f.......y.......
0010: 00 10 00 00 00 00 00 00 04 00 00 00 00 00 00 00 - ................
0020: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 - ................
ReadFile for inode 100180F66, offset=0
 key->inode=8000000100180F66; key->offset=0
 val->size=100000000001000; val->block=19EBB7; val->crypto_id=19EBB7
 key has offset 0
 val has block=19EBB7, size=1000
reading at offset 0 length 1000 starting from block 19EBB7 (extent starts at block 19EBB7)
dumping start of attribute content
0000: 66 70 6D 63 03 00 00 00 18 0B 00 00 00 00 00 00 - fpmc............
Compressed size B18 bytes.
    apfs_stat_internal => OK
apfs_open: 100180F65
GetAttribute: type=11
parsing as a link
 size=379 size_on_disk=1000
 inode says size=0 size_on_disk=0
dumping attribute link data
0000: 66 0F 18 00 01 00 00 00 79 03 00 00 00 00 00 00 - f.......y.......
0010: 00 10 00 00 00 00 00 00 04 00 00 00 00 00 00 00 - ................
0020: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 - ................
ReadFile for inode 100180F66, offset=0
 key->inode=8000000100180F66; key->offset=0
 val->size=100000000001000; val->block=19EBB7; val->crypto_id=19EBB7
 key has offset 0
 val has block=19EBB7, size=1000
reading at offset 0 length 1000 starting from block 19EBB7 (extent starts at block 19EBB7)
dumping start of attribute content
0000: 66 70 6D 63 03 00 00 00 18 0B 00 00 00 00 00 00 - fpmc............
Inode info: size=0, size_on_disk=0
DecompressFile 379 => B18, algo = 3
Expected B18 bytes in compressed stream, got 0

This also occurred with other .app files but not all of the ones in the image.

Any ideas?

Thank you!

**Comment by sgan81** [comment]
Not yet, but I will look into it when I have time (might be a few days)

**Comment by sgan81** [comment]
Hi again,

I need your help in fixing this. Can you get the newest version and try again, using -d 255? I need some more bytes after fpmc ...

Thanks.

**Comment by sgan81** [comment]
Fixed. Please get the newest version and tell me if it works. Thanks.
