### ISSUE TITLE
Block Device

### ISSUE THREAD

**Issue by vaishnavmurthy** [sgan81/apfs-fuse#43]
Hi there,
Thanks again for this tool, works great!
Would it be possible to create a block device file like dislocker does with dislocker-file and libewf does with ewf1 in addition to creating a mount directory?

Thanks!!

**Comment by sgan81** [comment]
Block device for what?

**Comment by vaishnavmurthy** [comment]
Block device of the decrypted volume, if possible so we can create an image of it (similar to the dislocker project). 
Not sure if that's even possible but wanted to check. 
Thanks!

**Comment by sgan81** [comment]
Ah, I understand. But no, it's not that easy, because partition = container, not volume, and to determine which blocks are encrypted and which ones are not (not all are), you need to parse all the filesystem information ... also, within one partition/container, you may have several encrypted volumes, each with a different key ...

**Comment by sgan81** [comment]
A volume can be anywhere within a container. A volume is not a partition (for which an offset would make sense), but more like a directory. The contents of a volume can be anywhere within a container.

If you wanted to decrypt a volume, you would do the following:
- Find out for each block to which volume and file it belongs, and if it is encrypted or not
- Decrypt the block
- Change the extent entry in the directory and set the iv block nr to 0
But there are snapshots, so doing the above directly might make those unusable ... so you would need to update those as well ... as you see, it is quite complicated.

You can use Apple's diskutil to decrypt apfs volumes.

**Comment by sgan81** [comment]
The problem is, apfs doesn't use full disk encryption like, for example, VeraCrypt / TrueCrypt, where you just can decrypt the whole disk and be done with it. In apfs, encryption is integrated deeply into the filesystem.
