### ISSUE TITLE
"-march=native" causes build failure on PPC64

### ISSUE THREAD

**Issue by hadess** [sgan81/apfs-fuse#44]
Not that it's super important to be able to build on PPC64 for this filesystem type, nonetheless, this error shows up when building on PPC64, and it looks easy enough to fix (removing it from the list of CFLAGS in `CMakeLists.txt`):
```
cc1plus: error: unrecognized command line option '-march=native'
```

**Comment by sgan81** [comment]
Ok, well, using -march=native is just an old habit of mine ...

Did you test this on a big-endian machine? Because if you did, I would be interested in hearing the results. Apfs-fuse should theoretically work on big-endian machines, but I never tested it myself ...

**Comment by hadess** [comment]
I'm afraid that I've never tested it on PPC64, and I don't know anyone that owns a PPC64 either (other than Fedora's build systems). I think little-endian PPC64s (as in, little endian user-space, the CPUs can be configured as either) are also a thing, and that big-endian ones are on the way out.

**Comment by hadess** [comment]
Fixed in https://github.com/sgan81/apfs-fuse/commit/fab316181eaa5c2a5403776e44ef7396dfa0773f
