### ISSUE TITLE
Possible semantic typo

### ISSUE THREAD

**Issue by Vogtinator** [sgan81/apfs-fuse#48]
I read the code out of curiosity and spotted this:

https://github.com/sgan81/apfs-fuse/blob/0ca2e1f5cdfe32613b662713dd9b87ddb82a96e7/apfsfuse/ApfsFuse.cpp#L187-L188

I suppose it should be

```
 st.st_atimespec.tv_sec = rec.ino.atime / div_nsec; 
 st.st_atimespec.tv_nsec = rec.ino.atime % div_nsec; 
```

**Comment by sgan81** [comment]
Wooops ... you're right. Thanks :-)

**Comment by sgan81** [comment]
Fixed.
