### ISSUE TITLE
ApfsDir::ReadFile strange assert

### ISSUE THREAD

**Issue by tomkoen** [sgan81/apfs-fuse#49]
What does this assert mean?
```
assert((size & 0xFFF) == 0);
```

It fails for most files (currently trying to extract a file which size is 3436)

**Comment by tomkoen** [comment]
Ok got it, you're expecting to read a file by 4096 blocks, right?

**Comment by sgan81** [comment]
Yes, the lib expects reads in multiples of block sizes. Just round up the file size to the next 4096-byte boundary, it should work.
