### ISSUE TITLE
Unnecessary dependency on libattr xattr.h.

### ISSUE THREAD

**Issue by httpLov3craft** [sgan81/apfs-fuse#54]
glibc version of the xattr.h header is more universally present, and nearly identical save an alias of ENOATTR for ENODATA. Recommend utilizing the glibc header for fewer dependencies which may not be easy to fulfill on all distributions. See #53 for a pull request.

**Comment by hadess** [comment]
`attr/xattr.h` is being removed from distributions, as per:
https://bugzilla.redhat.com/show_bug.cgi?id=1601482#c1

**Comment by sgan81** [comment]
Request #53 merged, should be fixed now.
