### ISSUE TITLE
Iterate the DMG archive contents. 

### ISSUE THREAD

**Issue by iradization** [sgan81/apfs-fuse#57]
Hi, 

I wonder if it’s possible to read the dmg contents using this project as a standalone version, without the need for fuse wrapper ? Where should I look for the relevant API’s for that ?

**Comment by sgan81** [comment]
Yes, use DeviceDMG (and all files on which it depends) in ApfsLib, all the necessary functions are there. You basically use open/read/close to read the dmg. I've actually already implemented that, might as well add the binary to the project ;)
