### ISSUE TITLE
Tried to build on macOS 10.11: "byteswap.h" is missing

### ISSUE THREAD

**Issue by SchmollTroll** [sgan81/apfs-fuse#6]
Hi there,

I tried to build apfs-fuse on OS X ElCapitan but OS X is missing the "byteswap.h" (this is a Mac problem in general). Could you please put your "byteswap.h" in the repository? Tnx!

**Comment by sgan81** [comment]
The header file byteswap.h is a gcc specific include file. However it's easy to write one yourself. Just define the functions bswap_16, bswap_32 and bswap_64. I'll have a look into that issue.

**Comment by dunhamsteve** [comment]
I was lazy, did "mdfind bswap_64", and then cribbed this from "snappy":

```c
#elif defined(__APPLE__)
// Mac OS X / Darwin features
#include <libkern/OSByteOrder.h>
#define bswap_16(x) OSSwapInt16(x)
#define bswap_32(x) OSSwapInt32(x)
#define bswap_64(x) OSSwapInt64(x)
```

Looks like it also will need an osx version of "DeviceLinux.cpp".

**Comment by trifle** [comment]
I've briefly waded through macOS missing dependencies. Here's what needs to be dealt with:

In cmake config:
- library icuuc is not available on linking (different name)

- byteswap.h (but dunhamsteve's fix worked)
- linux/fs.h doesn't exist, mac has sys/disk.h
- mac doesn't have BLKGETSIZE64 but DKIOCGETBLOCKCOUNT
- mac doesn't have O_LARGEFILE
- mac doesn't have pread64 but pread
- mac doesn't have Unicode.h, hence no Utf8toU32 and NormalizeFilename
- the bundled lzvn_decode.s from Rob Pike is too old and gives symbol errors for _lzvn_decode - newer version from his github repo fixes this
- mac has no attr/xattr.h; xattr functions on macOS take on additional argument for position (u_int32_t position)
- stat has different names for st_mtim etc, these are `st_mtimespec`, `st_ctimespec` and `st_atimespec`

With a bit of hacking, I could build the driver but it failed to open an APFS volume (attached a volume from a DMG via hdiutil attach -nomount -noverify to /dev/diskX and tried to mount that via apfs-fuse).

apfs-dump seemed to work!

I have absolutely no experience with C/C++, but these pointers might help!

**Comment by dunhamsteve** [comment]
Yeah, I just waded through the same process yesterday.  I'm multiplying block size by block count to get the size.

I guarded everything with appropriate ifdefs so it shouldn't break anything on other platforms, but I didn't quite get everything working:

The encryption stuff doesn't seem to work, it claims the passphrase is incorrect. (I haven't tried this image with linux yet, it could be a slightly different format.)

With an unencrypted image (using the block device for a partition holding the apfs container or an image thereof):

- `apfs-dump-quick` looks like it works.
- `apfs-dump` only seems to work off of a disk image, not a block device.
- `apfs-fuse` mounts, but returns I/O error when I try to `ls` the directory.

I ran apfs-fuse with `-o debug -d 1` and it looks like it's returning OK for GETATTR on inode 1, but the kernel module is unhappy with it.  It looks like inode 1 is hard-wired in the code, maybe it's missing some fields that the fuse driver wants. The output on the 

```unique: 2, opcode: GETATTR (3), nodeid: 1, insize: 40
apfs_getattr: ino=1 => OK
   unique: 2, error: 0 (Undefined error: 0), outsize: 128
unique: 2, opcode: GETATTR (3), nodeid: 1, insize: 40
apfs_getattr: ino=1 => OK
   unique: 2, error: 0 (Undefined error: 0), outsize: 128
```

To be honest, I was thinking of just checking in my progress and abandoning it (presuming Linux works for me), as I've found out that Sierra can read these filesystems, and I have other projects.  But I may find some more time to look at this further.

**Comment by sgan81** [comment]
dunhamsteve: Yes, node 1 is hardcoded. I assumed that this was the root node.
trifle: A raw image of a volume doesn't exist ... The partition is the container, and the volumes are within that container/partition. It's just like another layer in the filesystem hierarchy. In other words, an image of the volume would have the same size as an image of the container.

**Comment by sgan81** [comment]
Update: apfs-fuse now builds and runs on macOS.
