### ISSUE TITLE
Compile errors on Ubuntu 18.04

### ISSUE THREAD

**Issue by psybornut** [sgan81/apfs-fuse#65]
Hey, not really a developer of much, and know next to nothing about git, so not comfortable submitting anything officially.

I got this error while compiling:
`~/source/apfs-fuse/ApfsLib/Unicode.h:7:52: error: 'size_t' has not been declared.
`
I resolved this by opening the file and adding the following after the two includes:

`#include <cstdlib>`

That fixed it and was able to compile without further issues.

PS: I also had to install zlib1g-dev to get things working prior to this error.

**Comment by sgan81** [comment]
Should be fixed.
