### ISSUE TITLE
APFS read-only filesystem reference is available

### ISSUE THREAD

**Issue by Conan-Kudo** [sgan81/apfs-fuse#66]
Apple just dropped [the filesystem reference for APFS](https://developer.apple.com/support/apple-file-system/Apple-File-System-Reference.pdf) that covers reading the filesystem on non-Fusion Drive systems.

This should help with improving the support of the filesystem.

I've also attached it here in case it disappears for whatever reason: [Apple-File-System-Reference.pdf](https://github.com/sgan81/apfs-fuse/files/2406500/Apple-File-System-Reference.pdf)

**Comment by sgan81** [comment]
Yay :)

**Comment by sgan81** [comment]
Ok, the project has been refactored to use the official Apple names ;)
