### ISSUE TITLE
segmentation fault (core dumped)

### ISSUE THREAD

**Issue by jer-c** [sgan81/apfs-fuse#7]
I managed to compile apfs-fuse successfully, but when run with command
`sudo apfs-fuse /dev/sdb /mnt/osx`
it returns the error
`Segmentation fault (core dumped)`
any ideas where I should begin to get this tool working?
Itś running on Linux Mint 18.3.

**Comment by sgan81** [comment]
Hmmm ...

Can you compile the tool in debug mode (change CMAKE_BUILD_TYPE in the CMakeLists.txt), and then run the tool under gdb in order to find out where in the code the driver crashes?

**Comment by sgan81** [comment]
Also, usually you need to specify a partition as device. Like /dev/sdb2, for example.

**Comment by vessial** [comment]
Starting program: /home/vx/sourcecode/apple/apfs/apfs-fuse/build/bin/apfs-fuse /dev/loop8 /home/vx/sourcecode/apple/decompress/mnt/
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x000055555556cb02 in BTreeNode::level (this=0x0) at /home/vx/sourcecode/apple/apfs/apfs-fuse/ApfsLib/BTree.h:79
79              uint16_t level() const { return m_bt->level; }
(gdb) bt
#0  0x000055555556cb02 in BTreeNode::level (this=0x0) at /home/vx/sourcecode/apple/apfs/apfs-fuse/ApfsLib/BTree.h:79
#1  0x000055555556af20 in BTree::Lookup (this=0x55555579f538, result=..., key=0x7fffffffe270, key_size=16,
    func=0x555555561292 <CompareNodeMapKey(void const*, size_t, void const*, size_t, void*)>, context=0x55555579e538, exact=false)
    at /home/vx/sourcecode/apple/apfs/apfs-fuse/ApfsLib/BTree.cpp:212
#2  0x0000555555561629 in ApfsNodeMapperBTree::GetBlockID (this=0x55555579e538, info=..., nodeid=883424474293693973,
    version=13954203939649751056) at /home/vx/sourcecode/apple/apfs/apfs-fuse/ApfsLib/ApfsNodeMapperBTree.cpp:89
#3  0x000055555555d1ca in ApfsContainer::GetVolume (this=0x55555579de70, index=0)
    at /home/vx/sourcecode/apple/apfs/apfs-fuse/ApfsLib/ApfsContainer.cpp:98
#4  0x000055555555af95 in main (argc=3, argv=0x7fffffffe4d8) at /home/vx/sourcecode/apple/apfs/apfs-fuse/apfsfuse/ApfsFuse.cpp:594
(gdb)

**Comment by vessial** [comment]
as the command 
vx@vx-XPS-8910:~/sourcecode/apple/apfs/apfs-fuse/build$ sudo bin/apfs-fuse /dev/loop8 /home/vx/sourcecode/apple/decompress/mnt/          Segmentation fault
vx@vx-XPS-8910:~/sourcecode/apple/apfs/apfs-fuse/build$

**Comment by sgan81** [comment]
The segfault should be fixed by now. If not, let me know, otherwise I'm closing this issue.

**Comment by vessial** [comment]
appreciated!
