### ISSUE TITLE
Compile error in ubuntu 14.04 (And Fix)

### ISSUE THREAD

**Issue by kero99** [sgan81/apfs-fuse#70]
`/home/xxxx/apfs-fuse/ApfsDump/Apfs.cpp: In function ‘int main(int, const char**)’:
/home/xxxx/apfs-fuse/ApfsDump/Apfs.cpp:413:2: error: ‘unique_ptr’ is not a member of ‘std’
  std::unique_ptr<Device> dev_main;
  ^
/home/xxxx/apfs-fuse/ApfsDump/Apfs.cpp:413:24: error: expected primary-expression before ‘>’ token
  std::unique_ptr<Device> dev_main;
                        ^
/home/xxxx/apfs-fuse/ApfsDump/Apfs.cpp:413:26: error: ‘dev_main’ was not declared in this scope
  std::unique_ptr<Device> dev_main;
                          ^
/home/xxxx/apfs-fuse/ApfsDump/Apfs.cpp:414:2: error: ‘unique_ptr’ is not a member of ‘std’
  std::unique_ptr<Device> dev_tier2;
  ^
/home/xxxx/apfs-fuse/ApfsDump/Apfs.cpp:414:24: error: expected primary-expression before ‘>’ token
  std::unique_ptr<Device> dev_tier2;
                        ^
/home/xxxx/apfs-fuse/ApfsDump/Apfs.cpp:414:26: error: ‘dev_tier2’ was not declared in this scope
  std::unique_ptr<Device> dev_tier2;
                          ^
make[2]: *** [ApfsDump/CMakeFiles/apfs-dump.dir/Apfs.o] Error 1
make[2]: Leaving directory `/home/xxxx/apfs-fuse/build'
make[1]: *** [ApfsDump/CMakeFiles/apfs-dump.dir/all] Error 2
make[1]: Leaving directory `/home/xxxx/apfs-fuse/build'
make: *** [all] Error 2`

Fixed adding #include <memory> in the top of source files.

Best regards.

**Comment by sgan81** [comment]
Has been fixed.
