### ISSUE TITLE
Driver hangs reliably when listing extended attributes

### ISSUE THREAD

**Issue by ichernev** [sgan81/apfs-fuse#71]
When copying from a apfs-fuse volume with `-a (archive)` flag, the copy hangs reliably at the end of the first file. After `strace` I figured it is caused by `flistxattr` syscall that never returns.

The file itself is copied properly, its just the extended attributes that make it go bad.

This is reproducible with latest master c7036a3

**Comment by sgan81** [comment]
Thanks for the report. Fixed.
