### ISSUE TITLE
Error listing folders on image from mojave 10.14.2

### ISSUE THREAD

**Issue by ydkhatri** [sgan81/apfs-fuse#76]
When listing folders the following errors are seen and several folders cannot be browsed. This is using latest apfs-fuse on Ubuntu 14.04 32-bit. See below trying to run `ls -al` on root of mounted disk.
```
$ ls -al
ls: cannot access usr: Input/output error
ls: cannot access .DS_Store: Input/output error
ls: cannot access bin: Input/output error
ls: cannot access installer.failurerequests: Input/output error
ls: cannot access Network: Input/output error
ls: cannot access sbin: Input/output error
ls: cannot access .file: Input/output error
ls: cannot access etc: Input/output error
ls: cannot access var: Input/output error
ls: cannot access Library: Input/output error
ls: cannot access System: Input/output error
ls: cannot access private: Input/output error
ls: cannot access .vol: Input/output error
ls: cannot access Applications: Input/output error
ls: cannot access dev: Input/output error
ls: cannot access tmp: Input/output error
ls: cannot access cores: Input/output error
total 0
d????????? ? ?    ?     ?            ? Applications
d????????? ? ?    ?     ?            ? bin
d????????? ? ?    ?     ?            ? cores
d????????? ? ?    ?     ?            ? dev
d--x--x--x 1 root root  7 Jan  9 06:57 .DocumentRevisions-V100
-????????? ? ?    ?     ?            ? .DS_Store
l????????? ? ?    ?     ?            ? etc
-????????? ? ?    ?     ?            ? .file
drwx------ 1 root root 71 Jan  9 06:57 .fseventsd
dr-xr-xr-t 1 root root  0 Sep 25  2017 .HFS+ Private Directory Data?
dr-xr-xr-x 1 root root  0 Sep 25  2017 home
-????????? ? ?    ?     ?            ? installer.failurerequests
d????????? ? ?    ?     ?            ? Library
dr-xr-xr-x 1 root root  0 Sep 25  2017 net
d????????? ? ?    ?     ?            ? Network
drwxr-xr-x 1 root root  0 Jan  2 13:34 .PKInstallSandboxManager-SystemSoftware
d????????? ? ?    ?     ?            ? private
d????????? ? ?    ?     ?            ? sbin
drwx------ 1 root root  3 Sep 25  2017 .Spotlight-V100
d????????? ? ?    ?     ?            ? System
l????????? ? ?    ?     ?            ? tmp
d-wx-wx-wt 1 root root  0 Sep 25  2017 .Trashes
drwxr-xr-x 1 root root  5 Dec 28 13:11 Users
d????????? ? ?    ?     ?            ? usr
l????????? ? ?    ?     ?            ? var
d????????? ? ?    ?     ?            ? .vol
drwxr-xr-x 1 root root  1 Jan  9 06:57 Volumes

$ cd Applications
bash: cd: Applications: Input/output error

```

**Comment by chrhartung** [comment]
same problem on raspbian 9
Disk was created on MacOS Mojave 10.14.2 and is fully encrypted

**Comment by ydkhatri** [comment]
Mine was not encrypted.

**Comment by sgan81** [comment]
Strange ... never encountered this problem before.
Can you run it with -d 255, execute the ls -al and post the console output?

**Comment by ydkhatri** [comment]
> Can you run it with -d 255, execute the ls -al and post the console output?

Output was a little large, so attaching as files here:

[debug_on_mount.txt](https://github.com/sgan81/apfs-fuse/files/2891295/debug_on_mount.txt)
[debug_ls-al_root.txt](https://github.com/sgan81/apfs-fuse/files/2891294/debug_ls-al_root.txt)

**Comment by sgan81** [comment]
Thanks, I will look into that.

**Comment by sgan81** [comment]
Ok, I see the problem ... all files with inode numbers > 4G fail. Because fuse_ino_t is defined as unsigned long, which is 32 bits on 32-bit platforms, and APFS uses 64-bit object id's. This will be quite hard to get working on 32-bit platforms ...

**Comment by ydkhatri** [comment]
Thanks that makes sense. Perhaps you could also add a note to use only 64bit platform. Maybe even a check in code, so it can't be compiled on 32bit.

**Comment by sgan81** [comment]
Actually, the inode size has been defined as 64 bit in upstream since 2013, which would solve the problem ...
With a newer version of fuse than what you and I were using, this should actually be quite simple to fix. But I need to investigate a bit more.

**Comment by sgan81** [comment]
I have now updated apfs-fuse to use FUSE 3.0, it does now run properly on 32-bit systems.

You probably need to manually build and install fuse 3 on Ubuntu 14.04. The latest fuse version not requiring meson to build is fuse 3.1.1, which worked fine in my tests.

**Comment by ydkhatri** [comment]
Thanks, will take a look.
