### ISSUE TITLE
How to automount via fstab?

### ISSUE THREAD

**Issue by yurikoles** [sgan81/apfs-fuse#81]
Hello,

Thanks for great driver! I want to create fstab entry to mount my encrypted APFS volume on boot. How to do this?

**Comment by hyiltiz** [comment]
Can you even mount it when it is encrypted?

**Comment by yurikoles** [comment]
Yes, I supply password. But in my setup it's safe to put password in fstab, since my Linux system is also encrypted.

**Comment by sgan81** [comment]
Probably works if you copy or symlink the apfs-fuse binary to /usr/sbin/mount.apfs. At least you can mount/unmount with normal commands, so fstab will probably work as well.

**Comment by hyiltiz** [comment]
I tried to symlink or wrap it in a shell script as /usr/local/sbin/mount.apfs, but it kept saying: `unknown filesystem type 'apfs'.`. The `fstab` entry was:
```
UUID="THE-1st-UUID-REPORTED-BY-BLKID-FOR-APFS-DEV" /media/apfs apfs errors=remount-ro,noauto,user,ro 0 0
```

**Comment by yurikoles** [comment]
@hyiltiz
Works fine for me when I make symlink as suggested by @sgan81

I had putted `r=mypass` in fstab, but it still asks for password

**Comment by sgan81** [comment]
Sorry, supplying a password via fstab will not work with the current version, because passwords cannot be passed using -o. Will fix that in the next commit.

**Comment by sgan81** [comment]
You can now specify a passphrase via -o pass=... (or pass=... in fstab).

**Comment by yurikoles** [comment]
@sgan81 now it works, thanks!

**Comment by qgjdev** [comment]
Would someone kindly help me out here?
I'm trying to auto-mount an APFS volume through

(/etc/fstab)
`UUID=my123-uuid456-blablabla /mnt/apfs auto pass=mystr0ngp4$$w0rd 0 0`
using Gnome Disk Utility, but all I get in syslog is
```
Volume MacOS - Data is encrypted.
Mounted /dev/sda2 (system) at /mnt/apfs on behalf of uuid 1000
Cleaning up mount point /mnt/apfs (device 8:2 is not mounted)
```

My mounting options in Gnome Disk Utility state nothing but
`pass=mystr0ngp4$$w0rd`.

Thanks a lot in advance.

EDIT: BTW changing `auto` to `apfs` won't change anything.
