### ISSUE TITLE
Error compiler zlib.h

### ISSUE THREAD

**Issue by KaisenCAS** [sgan81/apfs-fuse#85]
apfs-fuse/ApfsLib/Util.cpp:36:10: fatal error: zlib.h: Aucun fichier ou dossier de ce type
 #include <zlib.h>
          ^~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/apfs.dir/build.make:427: CMakeFiles/apfs.dir/ApfsLib/Util.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:111: CMakeFiles/apfs.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

All dependancies installing. 

Thanks

**Comment by Banaanhangwagen** [comment]
When you read the *readme*, you'll see that `zlib` is a mandatory library.

Install it with `sudo apt install zlib1g-dev` and you'll be fine

**Comment by KaisenCAS** [comment]
Thanks you !
No error here ! 
Perfect
