### ISSUE TITLE
Apple File System Reference

### ISSUE THREAD

**Issue by Jensderond** [sgan81/apfs-fuse#89]
I assume this could help.. [Apple File System Reference](https://developer.apple.com/support/downloads/Apple-File-System-Reference.pdf) - (Source: https://developer.apple.com)

**Comment by Jensderond** [comment]
Information was already shared in #80

**Comment by RJVB** [comment]
Yes, I'd be surprised if this resource was unknown around here...

Am I right that it doesn't say anything about HFS/APFS compression?

**Comment by Jensderond** [comment]
@RJVB Yeah I figured.. 
The README of this project made me think otherwise by saying: `Since Apple didn't yet document the disk format of APFS, this driver should be considered experimental.`

**Comment by RJVB** [comment]
My experience with documents like this is that you only know if they're exhaustive when you start to try and implement a feature-complete implementation off of it. I can fully understand that the team consider their driver experimental if it is based on a document and not on a (complete) reference implementation (as there is/was for HFS).
